---
# =============================================================================
# FICHIER: send_email.yml
# OBJECTIF: Envoyer des emails de notification aux nouveaux utilisateurs
# DESCRIPTION: Playbook pour l'envoi automatique d'emails contenant les informations
#              de connexion après la création des comptes utilisateurs.
# USAGE: ansible-playbook -i inventory.ini send_email.yml
# NOTE: Ce playbook est généralement inclus depuis create_users.yml
# =============================================================================

# -----------------------------------------------------------------------------
# PLAY: Envoi des emails de bienvenue
# -----------------------------------------------------------------------------
- name: "Envoyer les notifications email aux nouveaux utilisateurs"
  
  # CIBLES: Mêmes serveurs que le playbook principal
  hosts: all
  
  # PRIVILÈGES: Pas d'élévation de privilèges nécessaire pour l'envoi d'emails
  become: no
  
  # VARIABLES: Chargement des variables partagées
  vars_files:
    - users_data.yaml
  
  # VARIABLES SPÉCIFIQUES AUX EMAILS
  vars:
    
    # -------------------------------------------------------------------------
    # PORT SSH: Port de connexion SSH distant
    # DÉFAUT: 22 (port standard SSH)
    # SÉCURITÉ: À modifier si le port SSH a été changé pour des raisons de sécurité
    # -------------------------------------------------------------------------
    ssh_port: "{{ ssh_port | default(22) }}"
    
    # -------------------------------------------------------------------------
    # ADRESSE IP DU SERVEUR: IP locale détectée automatiquement par Ansible
    # UTILISATION: Pour les connexions SSH depuis le réseau local
    # -------------------------------------------------------------------------
    server_ip: "{{ ansible_default_ipv4.address }}"
    
    # -------------------------------------------------------------------------
    # CONFIGURATION SMTP: Paramètres du serveur de messagerie
    # IMPORTANT: Ces valeurs DOIVENT être adaptées à votre environnement
    # SÉCURITÉ: Utiliser des variables d'environnement ou Ansible Vault en production
    # -------------------------------------------------------------------------
    
    # SERVEUR SMTP: Hôte du serveur de messagerie sortant
    # EXEMPLES: smtp.gmail.com, smtp.office365.com, smtp.mondomaine.com
    smtp_host: "smtp.gmail.com"
    
    # PORT SMTP: Port de connexion au serveur SMTP
    # STANDARD: 587 (STARTTLS), 465 (SSL/TLS), 25 (non chiffré, déconseillé)
    smtp_port: 587
    
    # IDENTIFIANT SMTP: Nom d'utilisateur pour l'authentification SMTP
    # FORMAT: Adresse email complète ou nom d'utilisateur selon le fournisseur
    smtp_username: "admin@monserveur.com"
    
    # MOT DE PASSE SMTP: Mot de passe ou token d'application
    # SÉCURITÉ: Pour Gmail, utiliser un "mot de passe d'application"
    #           Ne jamais stocker en clair en production - utiliser Ansible Vault
    smtp_password: "mot_de_passe_app"
  
  # -------------------------------------------------------------------------
  # SECTION: TÂCHES PRINCIPALES
  # -------------------------------------------------------------------------
  tasks:
    
    # -------------------------------------------------------------------------
    # TÂCHE 1: Récupération de l'adresse IP publique
    # OBJECTIF: Obtenir l'IP publique du serveur pour les connexions externes
    # CONDITION: Exécutée seulement si l'IP locale est dans une plage privée
    # NOTE: Utilise le service gratuit ipify.org
    # -------------------------------------------------------------------------
    - name: "Obtenir l'adresse IP publique du serveur"
      ansible.builtin.uri:
        
        # URL: Service web retournant l'IP publique
        url: "https://api.ipify.org"
        
        # RETOUR: Récupérer le contenu de la réponse (l'IP publique)
        return_content: yes
        
        # TIMEOUT: Délai maximum pour la requête (en secondes)
        timeout: 10
        
        # VALIDATION SSL: Vérifier le certificat SSL
        validate_certs: yes
      
      # ENREGISTREMENT: Stocker le résultat pour utilisation ultérieure
      register: public_ip
      
      # CONDITION: Seulement si l'IP locale est privée (RFC 1918)
      when: >
        server_ip.startswith('192.168.') or 
        server_ip.startswith('10.') or 
        server_ip.startswith('172.16.')
      
      # GESTION D'ERREURS: Continuer l'exécution même en cas d'échec
      ignore_errors: yes
    
    # -----------------------------------------------------------------------------
    # TÂCHE 2: Détermination de l'adresse IP de connexion
    # OBJECTIF: Choisir l'IP appropriée (publique ou locale) pour les instructions
    # LOGIQUE: IP publique si disponible, sinon IP locale
    # -----------------------------------------------------------------------------
    - name: "Déterminer l'adresse IP à utiliser dans les instructions"
      ansible.builtin.set_fact:
        
        # VARIABLE: IP de connexion finale
        # CONDITION: Utiliser l'IP publique si récupérée avec succès
        #            Sinon utiliser l'IP locale
        connection_ip: >-
          {% if public_ip is defined and public_ip is succeeded and public_ip.content %}
            {{ public_ip.content }}
          {% else %}
            {{ server_ip }}
          {% endif %}
    
    # ---------------------------------------------------------------------------------
    # TÂCHE 3: Envoi d'email à chaque utilisateur
    # OBJECTIF: Envoyer un email personnalisé à chaque nouvel utilisateur
    # NOTE: Boucle sur la liste des utilisateurs
    # SÉCURITÉ: Le mot de passe initial est inclus - à changer à la première connexion
    # ---------------------------------------------------------------------------------
    - name: "Envoyer l'email de bienvenue à {{ user.username }}"
      
      # BOUCLE: Itération sur tous les utilisateurs définis
      loop: "{{ users }}"
      
      # CONTRÔLE DE BOUCLE: Définition du nom de variable pour l'itération courante
      loop_control:
        loop_var: user
      
      # MODULE: Envoi d'email via SMTP
      ansible.builtin.mail:
        
        # -----------------------------------------------------------------
        # CONFIGURATION SMTP
        # -----------------------------------------------------------------
        
        # HÔTE: Serveur SMTP
        host: "{{ smtp_host }}"
        
        # PORT: Port SMTP
        port: "{{ smtp_port }}"
        
        # IDENTIFIANT: Nom d'utilisateur SMTP
        username: "{{ smtp_username }}"
        
        # MOT DE PASSE: Mot de passe SMTP
        password: "{{ smtp_password }}"
        
        # -----------------------------------------------------------------
        # DESTINATAIRE ET SUJET
        # -----------------------------------------------------------------
        
        # DESTINATAIRE: Adresse email de l'utilisateur
        to: "{{ user.email }}"
        
        # SUJET: Sujet de l'email avec personnalisation
        subject: "Création de compte - Serveur {{ inventory_hostname }}"
        
        # EXPÉDITEUR: Adresse de l'expéditeur (optionnel)
        # from: "Administration Système <admin@{{ inventory_hostname }}>"
        
        # -----------------------------------------------------------------
        # CORPS DE L'EMAIL (format HTML)
        # -----------------------------------------------------------------
        body: |
          <!DOCTYPE html>
          <html lang="fr">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Création de votre compte</title>
              <style>
                  body {
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                      line-height: 1.6;
                      color: #333;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                  }
                  .header {
                      background-color: #2c3e50;
                      color: white;
                      padding: 20px;
                      text-align: center;
                      border-radius: 5px 5px 0 0;
                  }
                  .content {
                      background-color: #f9f9f9;
                      padding: 30px;
                      border: 1px solid #ddd;
                      border-top: none;
                  }
                  .important {
                      background-color: #fff3cd;
                      border-left: 4px solid #ffc107;
                      padding: 15px;
                      margin: 20px 0;
                  }
                  .credentials {
                      background-color: #e9ecef;
                      padding: 15px;
                      border-radius: 5px;
                      font-family: 'Courier New', monospace;
                      margin: 15px 0;
                  }
                  .section {
                      margin: 25px 0;
                      padding-bottom: 15px;
                      border-bottom: 1px solid #eee;
                  }
                  .footer {
                      text-align: center;
                      margin-top: 30px;
                      padding-top: 20px;
                      border-top: 1px solid #ddd;
                      color: #666;
                      font-size: 0.9em;
                  }
                  h1, h2, h3 {
                      color: #2c3e50;
                  }
                  ul {
                      padding-left: 20px;
                  }
                  li {
                      margin-bottom: 8px;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>Votre compte a été créé</h1>
              </div>
              
              <div class="content">
                  <p>Bonjour <strong>{{ user.full_name }}</strong>,</p>
                  
                  <p>Votre compte utilisateur a été créé avec succès sur notre serveur.</p>
                  
                  <div class="section">
                      <h2>Informations de connexion</h2>
                      <ul>
                          <li><strong>Serveur :</strong> {{ connection_ip }}:{{ ssh_port }}</li>
                          <li><strong>Nom d'utilisateur :</strong> {{ user.username }}</li>
                          <li><strong>Mot de passe initial :</strong> {{ user.password }}</li>
                          <li><strong>Shell par défaut :</strong> {{ user.preferred_shell }}</li>
                      </ul>
                  </div>
                  
                  <div class="important">
                      <h3>Action requise : Changement de mot de passe</h3>
                      <p>Pour des raisons de sécurité, vous <strong>devez</strong> changer votre mot de passe 
                         immédiatement après votre première connexion.</p>
                  </div>
                  
                  <div class="section">
                      <h2>Connexion au serveur</h2>
                      <p>Pour vous connecter au serveur depuis un terminal :</p>
                      <div class="credentials">
                          ssh {{ user.username }}@{{ connection_ip }} -p {{ ssh_port }}
                      </div>
                  </div>
                  
                  <div class="section">
                      <h2>Configuration de la clé SSH (recommandé)</h2>
                      <p>Pour une connexion plus sécurisée sans mot de passe :</p>
                      
                      <h3>Sur Linux ou macOS :</h3>
                      <div class="credentials">
                          ssh-copy-id -p {{ ssh_port }} {{ user.username }}@{{ connection_ip }}
                      </div>
                      
                      <h3>Sur Windows (PowerShell) :</h3>
                      <div class="credentials">
                          type $env:USERPROFILE\.ssh\id_rsa.pub | ssh -p {{ ssh_port }} {{ user.username }}@{{ connection_ip }} "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
                      </div>
                  </div>
                  
                  <div class="section">
                      <h2>Informations complémentaires</h2>
                      <ul>
                          <li><strong>Quota disque :</strong> {{ disk_quota_gb }} Go maximum</li>
                          <li><strong>Accès sudo :</strong> Activé (commandes administratives)</li>
                          <li><strong>Restriction :</strong> Commande 'su' désactivée pour votre groupe</li>
                          <li><strong>Support :</strong> Contactez l'administrateur pour toute assistance</li>
                      </ul>
                  </div>
                  
                  <div class="footer">
                      <p>Ce message a été généré automatiquement.</p>
                      <p>Serveur : {{ inventory_hostname }} | Date : {{ ansible_date_time.date }}</p>
                      <p>Équipe d'administration système</p>
                  </div>
              </div>
          </body>
          </html>
        
        # -----------------------------------------------------------------
        # OPTIONS DU MESSAGE
        # -----------------------------------------------------------------
        
        # FORMAT: Email au format HTML
        subtype: html
        
        # CHIFFREMENT: Utilisation de STARTTLS (recommandé)
        secure: starttls
        
        # TIMEOUT: Délai maximum pour l'envoi (secondes)
        timeout: 30
        
        # PIÈCES JOINTES: Option pour ajouter des fichiers (optionnel)
        # attach:
        #   - /chemin/vers/fichier.txt
      
      # DÉLÉGATION: L'envoi est effectué depuis la machine de contrôle
      delegate_to: localhost
      
      # CONDITION: Envoyer seulement si l'utilisateur a une adresse email
      when: user.email | length > 0
      
      # JOURNALISATION: Enregistrer l'action
      register: email_result
      ignore_errors: yes
      
      # NOTIFICATION: Afficher le résultat
      changed_when: email_result is succeeded
      failed_when: email_result is failed
    
    # ---------------------------------------------------------------------
    # TÂCHE 4: Journalisation des résultats
    # OBJECTIF: Enregistrer les succès et échecs d'envoi d'emails
    # ---------------------------------------------------------------------
    - name: "Journaliser les résultats d'envoi d'emails"
      ansible.builtin.lineinfile:
        path: "{{ log_file | default('/var/log/ansible_email_notifications.log') }}"
        line: >-
          [{{ ansible_date_time.iso8601 }}] EMAIL - 
          Utilisateur: {{ user.username }} - 
          Email: {{ user.email }} - 
          Statut: {{ 'SUCCÈS' if email_result is succeeded else 'ÉCHEC' }}
        create: yes
      delegate_to: localhost
      when: email_result is defined
